print("North London Forever")
print("Get Ready for the Derby!")
print("Arsenal vs Tottenham!")
print("Come on you Gunners!")
print("North London is Red!")
print("North London is Red!")       
print("COYG!")
print("COYS!")
print("It's Derby Day!")
print("Derby Day is Here!")
print("North London United!")
print("Football Rivalry at its Best!")
print("Passion of North London!")
print("Rivalry and Respect!")
print("The North London Derby!")
print("END OF THE GAME!")
